[profile]
description = Default superpowers profile

[models]
brainstorm = opencode-go/qwen3.7-max
planner = opencode-go/kimi-k2.6
debugger = opencode-go/kimi-k2.6
execution-orchestrator = opencode-go/kimi-k2.5
software-engineer = opencode-go/kimi-k2.5
senior-software-engineer = opencode-go/kimi-k2.6
code-reviewer = opencode-go/deepseek-v4-pro
spec-reviewer = opencode-go/kimi-k2.5
utility = opencode-go/minimax-m2.7
